.TH "ak_ca_root" 3 "Sun Jul 17 2016" "akmalloc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ak_ca_root \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ak_ca_segment \fBmain_root\fP"
.br
.ti -1c
.RI "ak_ca_segment \fBempty_root\fP"
.br
.ti -1c
.RI "ak_free_list_node \fBfree_root\fP"
.br
.ti -1c
.RI "ak_u32 \fBnempty\fP"
.br
.ti -1c
.RI "ak_u32 \fBrelease\fP"
.br
.ti -1c
.RI "ak_u32 \fBRELEASE_RATE\fP"
.br
.ti -1c
.RI "ak_u32 \fBMAX_SEGMENTS_TO_FREE\fP"
.br
.ti -1c
.RI "ak_sz \fBMIN_SIZE_TO_SPLIT\fP"
.br
.ti -1c
.RI "ak_spinlock \fBLOCKED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The root for a coalescing allocator\&. 
.PP
Definition at line 1821 of file malloc\&.c\&.
.SH "Field Documentation"
.PP 
.SS "ak_ca_segment ak_ca_root::empty_root"
root of empty segments 
.PP
Definition at line 1824 of file malloc\&.c\&.
.SS "ak_free_list_node ak_ca_root::free_root"
root of the free list 
.PP
Definition at line 1826 of file malloc\&.c\&.
.SS "ak_spinlock ak_ca_root::LOCKED"
lock for this allocator if locks are enabled 
.PP
Definition at line 1836 of file malloc\&.c\&.
.SS "ak_ca_segment ak_ca_root::main_root"
root of non empty segments 
.PP
Definition at line 1823 of file malloc\&.c\&.
.SS "ak_u32 ak_ca_root::MAX_SEGMENTS_TO_FREE"
number of segments to free when release is done 
.PP
Definition at line 1832 of file malloc\&.c\&.
.SS "ak_sz ak_ca_root::MIN_SIZE_TO_SPLIT"
minimum size of split node to decide whether to split a free list node 
.PP
Definition at line 1833 of file malloc\&.c\&.
.SS "ak_u32 ak_ca_root::nempty"
number of empty segments 
.PP
Definition at line 1828 of file malloc\&.c\&.
.SS "ak_u32 ak_ca_root::release"
number of segments freed since last release 
.PP
Definition at line 1829 of file malloc\&.c\&.
.SS "ak_u32 ak_ca_root::RELEASE_RATE"
release rate for this root 
.PP
Definition at line 1831 of file malloc\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for akmalloc from the source code\&.
