.TH "ak_slab_root" 3 "Sun Jul 17 2016" "akmalloc" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ak_slab_root \- 
.SH SYNOPSIS
.br
.PP
.SS "Data Fields"

.in +1c
.ti -1c
.RI "ak_u32 \fBsz\fP"
.br
.ti -1c
.RI "ak_u32 \fBnpages\fP"
.br
.ti -1c
.RI "ak_u32 \fBnavail\fP"
.br
.ti -1c
.RI "ak_u32 \fBnempty\fP"
.br
.ti -1c
.RI "ak_u32 \fBrelease\fP"
.br
.ti -1c
.RI "ak_u32 \fB_unused\fP"
.br
.ti -1c
.RI "ak_slab \fBpartial_root\fP"
.br
.ti -1c
.RI "ak_slab \fBfull_root\fP"
.br
.ti -1c
.RI "ak_slab \fBempty_root\fP"
.br
.ti -1c
.RI "ak_u32 \fBRELEASE_RATE\fP"
.br
.ti -1c
.RI "ak_u32 \fBMAX_PAGES_TO_FREE\fP"
.br
.ti -1c
.RI "ak_spinlock \fBLOCKED\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Slab allocator 
.PP
Definition at line 1340 of file malloc\&.c\&.
.SH "Field Documentation"
.PP 
.SS "ak_u32 ak_slab_root::_unused"
for alignment 
.PP
Definition at line 1347 of file malloc\&.c\&.
.SS "ak_slab ak_slab_root::empty_root"
root of the empty slab list 
.PP
Definition at line 1351 of file malloc\&.c\&.
.SS "ak_slab ak_slab_root::full_root"
root of the full slab list 
.PP
Definition at line 1350 of file malloc\&.c\&.
.SS "ak_spinlock ak_slab_root::LOCKED"
lock for this allocator if locks are enabled 
.PP
Definition at line 1355 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::MAX_PAGES_TO_FREE"
number of pages to free when release happens 
.PP
Definition at line 1354 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::navail"
max number of available bits for the slab size \fCsz\fP 
.PP
Definition at line 1344 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::nempty"
number of empty pages 
.PP
Definition at line 1345 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::npages"
number of pages to obtain from the OS 
.PP
Definition at line 1343 of file malloc\&.c\&.
.SS "ak_slab ak_slab_root::partial_root"
root of the partially filled slab list 
.PP
Definition at line 1349 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::release"
number of accumulated free empty pages since last release 
.PP
Definition at line 1346 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::RELEASE_RATE"
number of pages moved to empty before a release 
.PP
Definition at line 1353 of file malloc\&.c\&.
.SS "ak_u32 ak_slab_root::sz"
the size of elements in this slab 
.PP
Definition at line 1342 of file malloc\&.c\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for akmalloc from the source code\&.
